# Generated by Django 5.1 on 2024-08-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
